# Generated by Django 5.2.13 on 2026-05-03 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('meat', 'Meat'), ('vegetables', 'Vegetables'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('gas', 'Gas'), ('utilities', 'Utilities'), ('refund', 'Refund'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField()),
                ('payment_source', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank')], max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('approved', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paidouts', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidouts', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
