# Generated by Django 5.2.13 on 2026-05-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidout',
            name='business_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidout',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paidout',
            name='vendor_payee',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
