# Generated by Django 5.2.13 on 2026-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidouts', '0002_paidout_business_date_paidout_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidout',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('meat', 'Meat'), ('vegetables', 'Vegetables'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('gas', 'Gas'), ('utilities', 'Utilities'), ('refund', 'Refund'), ('other', 'Other'), ('emergency_purchase', 'Emergency Purchase')], max_length=32),
        ),
    ]
