# Generated by Django 5.2.13 on 2026-05-04 01:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidouts', '0003_alter_paidout_category'),
        ('stores', '0002_historicalstore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaidOut',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('business_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('meat', 'Meat'), ('vegetables', 'Vegetables'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('gas', 'Gas'), ('utilities', 'Utilities'), ('refund', 'Refund'), ('other', 'Other'), ('emergency_purchase', 'Emergency Purchase')], max_length=32)),
                ('description', models.TextField()),
                ('vendor_payee', models.CharField(blank=True, max_length=160)),
                ('payment_source', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank')], max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=80)),
                ('receipt_image', models.TextField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stores.store')),
            ],
            options={
                'verbose_name': 'historical paid out',
                'verbose_name_plural': 'historical paid outs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
