# Generated by Django 5.2.13 on 2026-05-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=160)),
                ('business_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processed_inventory', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-business_date', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_id', models.CharField(blank=True, max_length=160)),
                ('item_name', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mapped_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.menuitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos_integrations.importedsale')),
            ],
        ),
        migrations.CreateModel(
            name='POSConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('clover', 'Clover'), ('square', 'Square'), ('toast', 'Toast'), ('csv', 'CSV'), ('other', 'Other')], max_length=32)),
                ('external_merchant_id', models.CharField(blank=True, max_length=160)),
                ('access_token', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_connections', to='clients.client')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_connections', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='importedsale',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pos_integrations.posconnection'),
        ),
        migrations.AlterUniqueTogether(
            name='importedsale',
            unique_together={('connection', 'external_order_id')},
        ),
    ]
