# Generated by Django 5.2.13 on 2026-05-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posconnection',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='sync_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
