# Generated by Django 5.2.13 on 2026-05-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_integrations', '0002_posconnection_last_error_posconnection_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedsale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='importedsale',
            name='processed_theoretical_usage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importedsale',
            name='status',
            field=models.CharField(default='imported', max_length=30),
        ),
        migrations.AddField(
            model_name='importedsale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='importedsale',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='connection_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
