# Generated by Django 5.2.13 on 2026-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_integrations', '0003_importedsale_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posconnection',
            name='api_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='client_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='external_location_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='scopes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posconnection',
            name='webhook_secret',
            field=models.TextField(blank=True),
        ),
    ]
