# Generated by Django 5.2.13 on 2026-05-03 10:23

from django.db import migrations, models


def split_existing_address(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    for client in Client.objects.exclude(address=''):
        if not client.street_address:
            client.street_address = client.address
            client.save(update_fields=['street_address'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(split_existing_address, migrations.RunPython.noop),
    ]
