# Generated by Django 5.2.13 on 2026-05-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorycount_inventorycountitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inventory_to_recipe_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inventory_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('gallon', 'gallon')], default='lb', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_to_inventory_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('gallon', 'gallon')], default='case', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('gallon', 'gallon')], default='lb', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target_food_cost_percentage',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor_invoices/'),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='tax_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereceiveitem',
            name='inventory_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('gallon', 'gallon')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereceiveitem',
            name='pack_size',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='purchasereceiveitem',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereceiveitem',
            name='purchase_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('gallon', 'gallon')], max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereceiveitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchasereceiveitem',
            name='vendor_item_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('gallon', 'gallon')], default='lb', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('gallon', 'gallon')], default='lb', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receive', 'Receive'), ('usage', 'Usage'), ('waste', 'Waste'), ('adjustment', 'Adjustment'), ('pos_deduction', 'POS Deduction'), ('theoretical', 'Theoretical Usage')], max_length=32),
        ),
    ]
