# Generated by Django 5.2.13 on 2026-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_average_cost_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='inventory_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('gal', 'gal'), ('qt', 'qt'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('jug', 'jug'), ('tub', 'tub'), ('gallon', 'gallon')], default='lb', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='purchase_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('gal', 'gal'), ('qt', 'qt'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('jug', 'jug'), ('tub', 'tub'), ('gallon', 'gallon')], default='case', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('gal', 'gal'), ('qt', 'qt'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('jug', 'jug'), ('tub', 'tub'), ('gallon', 'gallon')], default='lb', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('gal', 'gal'), ('qt', 'qt'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('jug', 'jug'), ('tub', 'tub'), ('gallon', 'gallon')], default='lb', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasereceiveitem',
            name='inventory_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('gal', 'gal'), ('qt', 'qt'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('jug', 'jug'), ('tub', 'tub'), ('gallon', 'gallon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereceiveitem',
            name='purchase_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('gal', 'gal'), ('qt', 'qt'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('jug', 'jug'), ('tub', 'tub'), ('gallon', 'gallon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('pcs', 'pcs'), ('piece', 'piece'), ('lb', 'lb'), ('oz', 'oz'), ('gal', 'gal'), ('qt', 'qt'), ('bag', 'bag'), ('case', 'case'), ('box', 'box'), ('jug', 'jug'), ('tub', 'tub'), ('gallon', 'gallon')], default='lb', max_length=20),
        ),
    ]
