# Generated by Django 5.2.13 on 2026-05-03 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_paidouts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_over', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to='stores.store')),
            ],
            options={
                'ordering': ['-business_date'],
                'unique_together': {('store', 'business_date')},
            },
        ),
    ]
