# Generated by Django 5.2.13 on 2026-05-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_historicalstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(default='yesterday', max_length=32)),
                ('question', models.TextField(blank=True)),
                ('report', models.JSONField(default=dict)),
                ('source', models.CharField(default='gemini', max_length=32)),
                ('mongo_document_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
